#!/usr/bin/env bash
# Install a nginx web server listening on port 80.
#
# Also, when querying nginx at its root / with a GET
# request, it returns a page that contains the string
# 'Hello World'.

sudo apt-get -y update
sudo apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee file /var/www/html/index.nginx-debian.html
sudo service nginx restart
