#!/usr/bin/env bash
# Install a nginx web server listening on port 80.
#
# Also, when querying nginx at its root / with a GET
# request, it returns a page that contains the string
# 'Hello World'.
#
# Also, the script, configure a directive of the Nginx server
# to redirect to another page with 301 HTTP Code

sudo apt-get -y update
sudo apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee file /var/www/html/index.nginx-debian.html
sudo sed -i '/server_name _;/a rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
