#!/usr/bin/env bash
# Configures a Ubuntu server with specific IP addresses
# to `localhost` and `facebook.com` hostname

cp /etc/hosts ~/hosts.new
sed -i 's/^127.*/127.0.0.2 localhost/' ~/hosts.new
sed -i '1 a 8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
